 --14. Find the total number of couriers handled by each employee. 

select e.Name, count(c.CourierID) as TotalCourier 
from Courier c
join EmployeeTable e on c.EmployeeID = e.EmployeeID
group by e.Name;
 

 
--15. Calculate the total revenue generated by each location 

select l.LocationName , sum(Amount) as TotalRevenue from payment p
join Location l on p.LocationID = l.LocationID
group by l.LocationName

--16. Find the total number of couriers delivered to each location.  

select l.LocationName , count(c.CourierID) from Location l
join Payment p on l.LocationID=p.LocationID
join Courier c on p.CourierID = c.CourierID
group by l.LocationName

--17. Find the courier with the highest average delivery time:  

select top 1 CourierID, avg(DeliveryTime) as AvgDeliveryTime 
from Courier 
group by CourierID 
order by AvgDeliveryTime desc 




--18. Find Locations with Total Payments Less Than a Certain Amount  
 select LocationName, sum(Amount) as TotalPayment
from Payment p join Location l on p.LocationID=l.LocationID
group by LocationName
having sum(Amount) < 200; 

--19. Calculate Total Payments per Location 

 select LocationName, sum(Amount) as TotalPayment
from Payment p join Location l on p.LocationID=l.LocationID
group by LocationName

--20. Retrieve couriers who have received payments totaling more than $1000 in a specific location (LocationID = X):  

select c.CourierID, c.SenderName, c.ReceiverName, sum(p.Amount) AS
TotalPayments from Courier c
join Payment p on c.CourierID = p.CourierID
where p.LocationID = 9
group by c.CourierID, c.SenderName, c.ReceiverName
having sum(p.Amount) > 100
order by TotalPayments ;


--21. Retrieve couriers who have received payments totaling more than $1000 after a certain date (PaymentDate > 'YYYY-MM-DD'):  
select c.CourierID, c.SenderName, c.ReceiverName, sum(p.Amount) AS
TotalPayments from Courier c
join Payment p on c.CourierID = p.CourierID
where p.PaymentDate > '2025-02-14'
group by c.CourierID, c.SenderName, c.ReceiverName
having sum(p.Amount) > 100
order by TotalPayments DESC;


--22. Retrieve locations where the total amount received is more than $5000 before a certain date (PaymentDate > 'YYYY-MM-DD')  

select p.LocationID, sum(p.Amount) as TotalAmtReceived
from Payment p
where p.PaymentDate < '2025-03-19' 
group by  p.LocationID
having sum(p.Amount) > 300
order by TotalAmtReceived ;